SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
EMAIL_USER = "nortonsantos79@gmail.com"
EMAIL_PASSWORD = "kdpz dujz qkni jsnp"
EMPRESA_NOME = "BarberSyst"
EMPRESA_TELEFONE = "(11) 99999-9999"
EMPRESA_ENDERECO = "Rua Exemplo, 123 - São Paulo, SP"